# Generated by Django 5.2.15 on 2026-07-01 19:48

from django.db import migrations, models


def populate_recipe_content(apps, schema_editor):
    Recipe = apps.get_model('recipebook', 'Recipe')
    recipes = {
        'pancake-cookies': {
            'description': 'More pancake than cookie, these baked goods are perfect for an on-the-go breakfast treat.',
            'ingredients': '\n'.join([
                '1/2 cup unsalted butter, melted',
                '3/4 cup granulated sugar',
                '1/4 cup brown sugar',
                '2 large eggs (optionally, reduce to 1)',
                '1 tsp pure almond extract (double for more flavor)',
                '1 tsp lemon juicer',
                '1/2 tsp baking soda',
                '1/2 tsp salt',
                '4 mashed ripe bananas',
                '2ish cups flour',
            ]),
            'steps': '\n'.join([
                'Slice the bananas into small chunks. Preheat oven to 350°F. Prepare two sheet pans and set aside.',
                'In a medium to large bowl, melt the butter. Add both sugars and whisk until fully incorporated.',
                'Add the egg, almond extract, and lemon juice. Whisk until the mixture is combined and smooth.',
                'Sprinkle the baking soda and salt over the mixture and stir well. Then add the flour and stir. Fold in the chopped bananas.',
                'Let chill in freezer or refrigerator to reduce expansion during baking.',
                'Use about 1 tbsp of dough for each cookie and leave plenty of space around each.',
                'Bake for about 12 minutes, until edges and bottoms are browned. Allow the cookies to cool on the pan before removing them.',
            ]),
        },
        'cake-cookies': {
            'description': 'A soft, sweet cookie recipe built from cake mix and pantry staples.',
            'ingredients': '\n'.join([
                '1 box cake mix',
                '2 eggs',
                '1/3 cup oil',
                'Optional mix-ins',
            ]),
            'steps': '\n'.join([
                'Preheat the oven to 350°F.',
                'Mix the cake mix, eggs, and oil until combined.',
                'Fold in any desired mix-ins.',
                'Scoop onto a baking sheet and bake until set.',
            ]),
        },
        'peach-croissant-dumplings': {
            'description': 'A warm, fruit-forward dessert with flaky pastry and sweet peach filling.',
            'ingredients': '\n'.join([
                'Croissant dough',
                'Peaches',
                'Sugar',
                'Butter',
            ]),
            'steps': '\n'.join([
                'Prepare the peach filling.',
                'Wrap with croissant dough.',
                'Bake until golden and serve warm.',
            ]),
        },
    }

    for slug, content in recipes.items():
        Recipe.objects.filter(slug=slug).update(**content)


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_seed_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(populate_recipe_content, migrations.RunPython.noop),
    ]
