# Generated by Django 5.2.15 on 2026-07-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0003_recipe_description_recipe_ingredients_recipe_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='page_url',
        ),
    ]
