# Generated by Django 5.2.15 on 2026-07-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0004_remove_recipe_page_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='order',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='published',
        ),
    ]
