# Generated by Django 5.2.15 on 2026-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0005_alter_recipe_options_remove_recipe_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='border',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
