# Generated by Django 5.2.15 on 2026-07-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0006_recipe_border'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='border',
            field=models.CharField(max_length=32),
        ),
    ]
